### ISSUE TITLE
Error  al guardar un producto nuevo

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#26]
Estimados,
Se está presentando este error al momento de crear productos, siempre los hemos creado de la misma forma.
![image001](https://user-images.githubusercontent.com/7632703/28537932-1b1ccdde-7072-11e7-9a3a-8d4e32074faa.jpg)

Gonzalo Márquez 
Líder de Operaciones - GDS Perú

**Comment by lisbethgutierrez** [comment]
Se ha reproducido el error presentado por la empresa GDS del Perú,
el cual se presenta al ingresar a Ventas / Productos / Productos  Crear, se llenan los campos obligatorios y necesarios, y al GUARDAR muestra el siguiente mensaje:

```
Error 
Invalid Type
```

Código

> 2017-07-24 18:13:12,574 1097 ERROR demope_02 cubicerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/http.py", line 545, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/http.py", line 582, in dispatch
    result = self._call_function(**self.params)
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/http.py", line 318, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/http.py", line 315, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/http.py", line 811, in __call__
    return self.method(*args, **kw)
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/http.py", line 411, in response_wrap
    response = f(*args, **kw)
  File "/home/cubicerp_v9/cbc/cubicerp/addons/web/controllers/main.py", line 965, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/cubicerp_v9/cbc/cubicerp/addons/web/controllers/main.py", line 957, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/cubicerp_v9/cbc/cubicerp/addons/product/product.py", line 742, in create
    product_template_id = super(product_template, self).create(cr, uid, vals, context=context)
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/cubicerp_v9/cbc/cubicerp/addons/mail/mail_thread.py", line 381, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/models.py", line 4100, in create
    if unknown:
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/models.py", line 4291, in _create
    del rel_context[c[0]]
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/osv/fields.py", line 1483, in set
    self._fnct_inv(obj, cr, user, id, name, value, self._fnct_inv_arg, context)
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/osv/fields.py", line 1719, in _property_write
    ir_property.set_multi(cr, uid, prop_name, obj._name, {id: value}, context=context)
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/addons/base/res/ir_property.py", line 265, in set_multi
    ('group_id', '=', group_id),
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/addons/base/res/ir_property.py", line 124, in create
    raise ValueError()
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/cubicerp_v9/cbc/cubicerp/openerp/addons/base/res/ir_property.py", line 101, in _update_values
   except_orm: ('Error', 'Invalid type')

**Comment by yurytello** [comment]
Se ha reiniciado el servidor gunicorn y aparentemente el problema esta solucionado, verificar por favor.

Saludos
