### ISSUE TITLE
email error : posting a message without model should be with a parent_id (private mesage).

### ISSUE THREAD

**Issue by Nucleoos** [CubicERP/cubicerp#33]
I am trying to use the email functionality and this error is occurring.
2017-09-12 14:17:01,809 3219 ERROR MEC openerp.addons.fetchmail.fetchmail: Failed to process mail from imap server rogerio.p.falcone@gmail.com.
Traceback (most recent call last):
  File "/opt/core/addons/fetchmail/fetchmail.py", line 215, in fetch_mail
    context=context)
  File "/opt/core/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/core/addons/mail/mail_thread.py", line 1215, in message_process
    routes = self.message_route(cr, uid, msg_txt, msg, model, thread_id, custom_values, context=context)
  File "/opt/core/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/core/addons/mail/mail_thread.py", line 1098, in message_route
    update_author=True, assert_model=True, context=context)
  File "/opt/core/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/core/addons/mail/mail_thread.py", line 852, in message_route_verify
    raise ValueError('Routing: posting a message without model should be with a parent_id (private mesage).')
ValueError: Routing: posting a message without model should be with a parent_id (private mesage).

**Comment by yurytello** [comment]
Hi Rogerio, which option you use to raise this error, please explain the steps to reproduce the error.

Regards
