### ISSUE TITLE
NO funciona el Botón Pagar ahora - Negolatina

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#41]
![paynow](https://user-images.githubusercontent.com/7632703/31786457-2c7228f4-b4ce-11e7-99a2-328baff80c73.png)

**Comment by lisbethgutierrez** [comment]
Se replicó el error reportado por el cliente a la hora de procesar una compra mediante la Tienda Virtual, en la que al llegar al paso de PAGAR AHORA no cambia de estado a CONFIRMADO y tampoco se procesa la compra.
Se ha revisado el Código mediante la interfaz y todo aparentemente esta correcto.
Verificando el log al momento de dar clic en el botón PAGAR AHORA muestra el siguiente mensaje:

```
2017-10-19 17:58:50,577 1309 ERROR NEGOLATINA cubicerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/cubicerp/cbc/cubicerp/openerp/http.py", line 545, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/cubicerp/cbc/cubicerp/openerp/http.py", line 582, in dispatch
    result = self._call_function(**self.params)
  File "/home/cubicerp/cbc/cubicerp/openerp/http.py", line 318, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/cubicerp/cbc/cubicerp/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/cubicerp/cbc/cubicerp/openerp/http.py", line 315, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/cubicerp/cbc/cubicerp/openerp/http.py", line 811, in __call__
    return self.method(*args, **kw)
  File "/home/cubicerp/cbc/cubicerp/openerp/http.py", line 411, in response_wrap
    response = f(*args, **kw)
  File "/home/cubicerp/cbc/cubicerp/addons/website_sale/controllers/main.py", line 761, in payment_transaction
    }, context=context)
  File "/home/cubicerp/cbc/cubicerp/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/cubicerp/cbc/cubicerp/addons/payment/models/payment_acquirer.py", line 369, in create
    partner = self.on_change_partner_id(cr, uid, None, values.get('partner_id'), context=context)['values']
TypeError: on_change_partner_id() takes exactly 1 argument (6 given)

```

**Comment by yurytello** [comment]
Actualizar la versión y reportar ya que estamos trabajando en el módulo de pagos en este momento

Saludos
