### ISSUE TITLE
ERROR al hacer clic en el boton EXTRACT QUERY del JOB del ETL 

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#55]
Al subir en el Job el archivo **.txt** de la Base de datos de Chiledar  y hacer clic en el Botón **EXTRACT QUERY**, muestra el siguiente mensaje:

**Archivo:** CBS Security monobanco.txt

```
Error:
CubicERP Server Error

Traceback (most recent call last):
  File "/usr/lib/python3.5/configparser.py", line 1135, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'chiledar_201801'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/v2018/cbc/cubicerp/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/v2018/cbc/cubicerp/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/v2018/cbc/cubicerp/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/v2018/cbc/cubicerp/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/v2018/cbc/cubicerp/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/v2018/cbc/cubicerp/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/v2018/cbc/cubicerp/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/v2018/cbc/cubicerp/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/v2018/cbc/cubicerp/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/v2018/cbc/cubicerp/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/v2018/cbc/cubicerp/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/v2018/cbc/cubicerp/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/v2018/cbc/cubicerp/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/v2018/cbc/branch/etl/models/etl.py", line 188, in do_extract
    oer_local = cbc_xmlrpc.get_connection(self._cr.dbname)
  File "/usr/local/lib/python3.5/dist-packages/cubicerpetl/cbc_xmlrpc.py", line 44, in get_connection
    hostname = parser.get(database, 'host')
  File "/usr/lib/python3.5/configparser.py", line 778, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.5/configparser.py", line 1138, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'chiledar_201801'
```

**Comment by lisbethgutierrez** [comment]
Se dio de alta el siguiente BUG mediante el parche [d09dce4](https://github.com/CubicERP/cubicerp-client-etl/commit/d09dce493a6dcd02fd23f032c044b54680f90111) **[FIX] cubicerp etl** y mediante la configuranción del archivo **config.ini** de la librería **cubicerp-client-etl** en` :~/cubicerp-client-etl/cubicerpetl$ nano config.ini` y creando el archivo de configuración en la siguiente dirección: `sudo nano /usr/local/lib/python3.5/dist-packages/cubicerpetl/config.ini` 

Ajustar el contenido del archivo de configuración: **config.ini** 
```
[pos_demo_01]
host = 127.0.0.1
port = 6989
username = admin
password = amin

```
Según los accesos de la Base de Datos y servidor al que se desea acceder.
