### ISSUE TITLE
Internal Server Error omegaindperu.com

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#59]
Al ingresar la página [omegaindperu.com](omegaindperu.com) se muestra de la siguiente forma.
![inter](https://user-images.githubusercontent.com/7632703/35928567-78a8d14e-0bfb-11e8-86e5-9cb60cfd25c1.png)

**Comment by lisbethgutierrez** [comment]
Se procedió ha actualizar la página de [omegaindperu.com](omegaindperu.com) y al realisarlo, casi al final muestra el siguiente error.

```
2018-02-07 16:33:14,606 32056 INFO omegaindperu cubicerp.tools.translate: no changes /home/w8/cbc/cubicerp/addons/payment_transfer/i18n/es_PE.po
2018-02-07 16:33:14,611 32056 CRITICAL omegaindperu cubicerp.service.server: Failed to initialize database `omegaindperu`.
Traceback (most recent call last):
  File "/home/w8/cbc/cubicerp/openerp/service/server.py", line 937, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/w8/cbc/cubicerp/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/w8/cbc/cubicerp/openerp/modules/loading.py", line 390, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/w8/cbc/cubicerp/openerp/modules/loading.py", line 294, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/w8/cbc/cubicerp/openerp/modules/loading.py", line 190, in load_module_graph
    models = registry.load(cr, package)
  File "/home/w8/cbc/cubicerp/openerp/modules/registry.py", line 163, in load
    model = cls._build_model(self, cr)
  File "/home/w8/cbc/cubicerp/openerp/models.py", line 595, in _build_model
    original_module = pool[name]._original_module if name in parents else cls._module
  File "/home/w8/cbc/cubicerp/openerp/modules/registry.py", line 102, in __getitem__
    return self.models[model_name]
KeyError: 'stock.move'

```
