### ISSUE TITLE
Error al momento de crear la base de datos

### ISSUE THREAD

**Issue by daniel020416** [CubicERP/cubicerp#60]
CubicERP Server Error

Traceback (most recent call last):
  File "/home/cubicerp/cubicerp/openerp/http.py", line 545, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/cubicerp/cubicerp/openerp/http.py", line 582, in dispatch
    result = self._call_function(**self.params)
  File "/home/cubicerp/cubicerp/openerp/http.py", line 319, in _call_function
    return self.endpoint(*args, **kwargs)
  File "/home/cubicerp/cubicerp/openerp/http.py", line 811, in __call__
    return self.method(*args, **kw)
  File "/home/cubicerp/cubicerp/openerp/http.py", line 411, in response_wrap
    response = f(*args, **kw)
  File "/home/cubicerp/cubicerp/addons/web/controllers/main.py", line 719, in create
    params.get('template_db',''))
  File "/home/cubicerp/cubicerp/openerp/http.py", line 887, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/home/cubicerp/cubicerp/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/cubicerp/cubicerp/openerp/service/db.py", line 86, in dispatch
    security.check_super(passwd)
  File "/home/cubicerp/cubicerp/openerp/service/security.py", line 32, in check_super
    raise openerp.exceptions.AccessDenied()
AccessDenied: Access denied.

Como lo soluciono?

**Comment by lisbethgutierrez** [comment]
Estimado Daniel, 
si el mensaje le muestra al tratar de crear la Base de datos, el BUG se debe a que esta colocando la clave maestra errónea, intentar con **admin**

de no superar el BUG con ello pedirle que nos brinde mayor detalle al respecto para poder ayudarlo.

Saludos.

**Comment by daniel020416** [comment]
Estimada Lisbeth,

Muchas gracias. tenias razon... esta genial CubicERP
