### ISSUE TITLE
BUG en Actualizar el stock desde el Producto

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#61]
Se trato de actualizar el stock de un producto desde la opción de Ventas / Productos  / Productos - productos pestaña inventario y al ingresar la cantidad muestra el siguiente mensaje:

```
CubicERP Server Error
Traceback (most recent call last):
  File "/home/w8/cbc/cubicerp/openerp/http.py", line 545, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/w8/cbc/cubicerp/openerp/http.py", line 582, in dispatch
    result = self._call_function(**self.params)
  File "/home/w8/cbc/cubicerp/openerp/http.py", line 318, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/w8/cbc/cubicerp/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/w8/cbc/cubicerp/openerp/http.py", line 315, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/w8/cbc/cubicerp/openerp/http.py", line 811, in __call__
    return self.method(*args, **kw)
  File "/home/w8/cbc/cubicerp/openerp/http.py", line 411, in response_wrap
    response = f(*args, **kw)
  File "/home/w8/cbc/cubicerp/addons/web/controllers/main.py", line 969, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/w8/cbc/cubicerp/addons/web/controllers/main.py", line 957, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/w8/cbc/cubicerp/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/w8/cbc/cubicerp/addons/stock/wizard/stock_change_product_qty.py", line 123, in change_product_qty
    inventory_id = inventory_obj.create(cr, uid, self._prepare_inventory(cr, uid, data, context=context), context=context)
  File "/home/w8/cbc/cubicerp/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/w8/cbc/branch/stock_analytic/wizard/stock_change_product_qty.py", line 31, in _prepare_inventory
    res = super(stock_change_product_qty, self)._prepare_inventory_line(cr, uid, data, context=context)
  File "/home/w8/cbc/cubicerp/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
TypeError: _prepare_inventory_line() takes at least 5 arguments (5 given)
```

**Comment by lisbethgutierrez** [comment]
Se a superado este bug mediante la realización de un parche. 
El cambio ya se refleja en las Bases de Datos de la nube actualizadas.
![cantmano](https://user-images.githubusercontent.com/7632703/50664794-52249000-0f7c-11e9-912d-49b4dc85ab7e.png)
