### ISSUE TITLE
Error al crear BD luego de la instalación

### ISSUE THREAD

**Issue by alenguav** [CubicERP/cubicerp#64]
Seguí las instrucciones del readme en español y a pesar de que no saltó ningún error,
me salió el siguiente mensaje cuando traté de crear la BD de demo.

Traceback (most recent call last):
  File "/home/cubicerp/cubicerp/openerp/http.py", line 545, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/cubicerp/cubicerp/openerp/http.py", line 582, in dispatch
    result = self._call_function(**self.params)
  File "/home/cubicerp/cubicerp/openerp/http.py", line 319, in _call_function
    return self.endpoint(*args, **kwargs)
  File "/home/cubicerp/cubicerp/openerp/http.py", line 811, in __call__
    return self.method(*args, **kw)
  File "/home/cubicerp/cubicerp/openerp/http.py", line 411, in response_wrap
    response = f(*args, **kw)
  File "/home/cubicerp/cubicerp/addons/web/controllers/main.py", line 719, in create
    params.get('template_db',''))
  File "/home/cubicerp/cubicerp/openerp/http.py", line 887, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/home/cubicerp/cubicerp/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/cubicerp/cubicerp/openerp/service/db.py", line 86, in dispatch
    security.check_super(passwd)
  File "/home/cubicerp/cubicerp/openerp/service/security.py", line 32, in check_super
    raise openerp.exceptions.AccessDenied()
AccessDenied: Access denied.

**Comment by alenguav** [comment]
No había recordado que debía usar "admin" como contraseña maestra

**Comment by lisbethgutierrez** [comment]
Efectivamente, la clave maestra al crear la BD es **_admin_**
