### ISSUE TITLE
ImportError: No module named 'brand'

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#65]
Se migro el módulo **_product_brand_** al repositorio Branch, se ingresó por la URL a la Base de Datos, se filtró el módulo **_product_brand_**
![product_brand](https://user-images.githubusercontent.com/7632703/37542554-94cbaef2-292c-11e8-9d0a-fe2121f395df.png)

Se trató de instalar el módulo **_product_brand_** y mostró el siguiente mensaje:
```
2018-03-16 19:53:23,599 5743 CRITICAL demo_peru_02 cubicerp.modules.module: Couldn't load module product_brand
2018-03-16 19:53:23,599 5743 CRITICAL demo_peru_02 cubicerp.modules.module: No module named 'brand'
2018-03-16 19:53:23,599 5743 ERROR demo_peru_02 cubicerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/v2018beta/cubicerp/odoo/modules/registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/v2018beta/cubicerp/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/home/v2018beta/cubicerp/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/v2018beta/cubicerp/odoo/modules/loading.py", line 121, in load_module_graph
    load_openerp_module(package.name)
  File "/home/v2018beta/cubicerp/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/home/v2018beta/cubicerp/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 20, in <module>
ImportError: No module named 'brand'
2018-03-16 19:53:23,613 5743 ERROR demo_peru_02 odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/v2018beta/cubicerp/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/v2018beta/cubicerp/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/v2018beta/cubicerp/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/v2018beta/cubicerp/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/v2018beta/cubicerp/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/v2018beta/cubicerp/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/v2018beta/cubicerp/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/v2018beta/cubicerp/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/v2018beta/cubicerp/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/v2018beta/cubicerp/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/v2018beta/cubicerp/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/v2018beta/cubicerp/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/v2018beta/cubicerp/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/home/v2018beta/cubicerp/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/v2018beta/cubicerp/odoo/addons/base/module/module.py", line 446, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/v2018beta/cubicerp/odoo/addons/base/module/module.py", line 539, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/v2018beta/cubicerp/odoo/modules/registry.py", line 84, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/v2018beta/cubicerp/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/home/v2018beta/cubicerp/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/v2018beta/cubicerp/odoo/modules/loading.py", line 121, in load_module_graph
    load_openerp_module(package.name)
  File "/home/v2018beta/cubicerp/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/home/v2018beta/cubicerp/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 20, in <module>
ImportError: No module named 'brand'
```

**Comment by yurytello** [comment]
https://github.com/CubicERP/branch/commit/e0e28d9467992102464ed514f4135180a00e01bd
