### ISSUE TITLE
Mensajes de error al importar BD

### ISSUE THREAD

**Issue by alenguav** [CubicERP/cubicerp#66]
Entiendo que el comando  `./cubicerp-server -c .cubicerp_serverrc -d <base_de_datos> -u all -F`
sirve para importar la data de CubicERP en una BD creada desde la interfaz web 
Dicho esto me pregunto si es normal que aparezcan los siguientes mensajes de error durante su ejecución
```

   return super(JsonRequest, self)._handle_exception(exception)
  File "/home/cubicerp/cubicerp/openerp/http.py", line 1444, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1483, in match
    raise NotFound()
NotFound: 404: Not Found
2018-03-16 21:31:33,550 28876 INFO None werkzeug: 179.7.68.79 - - [16/Mar/2018 21:31:33] "POST /longpolling/poll HTTP/1.1" 200 -
2018-03-16 21:31:44,183 28876 ERROR None cubicerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/cubicerp/cubicerp/openerp/http.py", line 545, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/cubicerp/cubicerp/openerp/http.py", line 1444, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1483, in match
    raise NotFound()
NotFound: 404: Not Found
2018-03-16 21:31:44,184 28876 INFO None werkzeug: 179.7.68.79 - - [16/Mar/2018 21:31:44] "POST /longpolling/poll HTTP/1.1" 200 -
2018-03-16 21:32:01,817 28876 ERROR None cubicerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/cubicerp/cubicerp/openerp/http.py", line 545, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/cubicerp/cubicerp/openerp/http.py", line 1444, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1483, in match
    raise NotFound()
NotFound: 404: Not Found
2018-03-16 21:32:01,818 28876 INFO None werkzeug: 179.7.68.79 - - [16/Mar/2018 21:32:01] "POST /longpolling/poll HTTP/1.1" 200 -
2018-03-16 21:32:02,129 28876 ERROR None cubicerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/cubicerp/cubicerp/openerp/http.py", line 545, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/cubicerp/cubicerp/openerp/http.py", line 1444, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1483, in match
    raise NotFound()
NotFound: 404: Not Found
2018-03-16 21:32:02,130 28876 INFO None werkzeug: 179.7.68.79 - - [16/Mar/2018 21:32:02] "POST /longpolling/poll HTTP/1.1" 200 -



```

**Comment by alenguav** [comment]
Al final, reinstalé todo de nuevo y si bien ya no me salen errores.
Sigo viendo las mismas aplicaciones "por instalar" cuando me logueo a la base de datos que supuestamente se estaba actualizando por el comando: `./cubicerp-server -c .cubicerp_serverrc -d <base_de_datos> -u all -F`

**Comment by lisbethgutierrez** [comment]
Si es la version 2018 la que esta intentando instalar, el comando `./cubicerp-server -c .cubicerp_serverrc` le permite levantar el servicio. Si desea actualizar la Base de Datos debe usar el siguiente comando: `./cubicerp-server -c .cubicerp_serverrc -d <base_de_datos> -u all`.

Una vez creada la Base de Datos debe empezar instalando el modulo **_account_accountant_**, account_report, purchase, stock, account_annul, account_cancel, ... etc.

**Nota:** 
Para instalar el modulo **_Sale_**, antes debe instalar algunos módulos (como base los antes mencionados antes de instalar este módulo).

**Comment by alenguav** [comment]
¿Y como sé si el comando `./cubicerp-server -c .cubicerp_serverrc -d <base_de_datos> -u all`
terminó su tarea?

**Comment by lisbethgutierrez** [comment]
Uno es cuando deja de correr el código en el promt y otra forma de identificar es que cuando ha dejado de correr el código en el promt, en las últimas líneas del código dice esto: ir_ui_menu...
