### ISSUE TITLE
CubicERP Server Error al crear un Usuario en BD de Tippic

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#67]
Se ha replicado el Error reportado por la empresa tippic en su BD **tippic2018** cuando intenta registrar un usuario, mostrandole el siguiente mensaje:

```
Error:
CubicERP Server Error

Traceback (most recent call last):
  File "/home/cubicerp/cbc/cubicerp/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/cubicerp/cbc/cubicerp/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/cubicerp/cbc/cubicerp/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/cubicerp/cbc/cubicerp/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/cubicerp/cbc/cubicerp/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/cubicerp/cbc/cubicerp/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/cubicerp/cbc/cubicerp/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/cubicerp/cbc/cubicerp/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/cubicerp/cbc/cubicerp/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/cubicerp/cbc/cubicerp/addons/web/controllers/main.py", line 924, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/cubicerp/cbc/cubicerp/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/cubicerp/cbc/cubicerp/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/cubicerp/cbc/cubicerp/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/cubicerp/cbc/cubicerp/addons/sales_team/models/res_users.py", line 17, in create
    user = super(ResUsers, self).create(vals)
  File "/home/cubicerp/cbc/cubicerp/addons/auth_signup/models/res_users.py", line 144, in create
    user = super(ResUsers, self).create(values)
  File "/home/cubicerp/cbc/cubicerp/addons/mail/models/res_users.py", line 56, in create
    user = super(Users, self).create(values)
  File "/home/cubicerp/cbc/cubicerp/odoo/addons/base/res/res_users.py", line 796, in create
    user = super(UsersView, self).create(values)
  File "/home/cubicerp/cbc/cubicerp/odoo/addons/base/res/res_users.py", line 642, in create
    return super(UsersImplied, self).create(values)
  File "/home/cubicerp/cbc/cubicerp/odoo/addons/base/res/res_users.py", line 325, in create
    user = super(Users, self).create(vals)
  File "/home/cubicerp/cbc/cubicerp/odoo/models.py", line 3281, in create
    record = self.browse(self._create(old_vals))
  File "/home/cubicerp/cbc/cubicerp/odoo/models.py", line 3338, in _create
    parent_id = self.env[parent_model].create(parent_vals).id
  File "/home/cubicerp/cbc/branch/base_person/models/res_partner.py", line 46, in create
    if len(names) > 2:
TypeError: object of type 'filter' has no len()
```

**Comment by yurytello** [comment]
corrected!
