### ISSUE TITLE
BUG el botón agregar nota de Crédito - Tippic v2018

### ISSUE THREAD

**Issue by lisbethgutierrez** [CubicERP/cubicerp#71]
![image](https://user-images.githubusercontent.com/7632703/40261051-10d79ef2-5ac4-11e8-9439-5963e876523b.png)

**Comment by lisbethgutierrez** [comment]
Se ha replicado el Bug reportado por la empresa TIPPIC, en el cual cunado se ingresa a una factura y se da clic en el Botón **AGREGAR NOTA DE CRÉDITO** : ![image](https://user-images.githubusercontent.com/7632703/40261105-6bdd6b74-5ac4-11e8-9909-eed109d16f8e.png) , muestra la siguiente ventana:
![image](https://user-images.githubusercontent.com/7632703/40261146-a25bdd84-5ac4-11e8-97f3-829734633c63.png)
Se completo los datos y una vez que se dio clic en el Botón AGREGAR NOTA DE CRÉDITO, muestra el siguiente mensaje de error:
Error:
CubicERP Server Error

```
Traceback (most recent call last):
  File "/home/cubicerp/cbc/cubicerp/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/cubicerp/cbc/cubicerp/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/cubicerp/cbc/cubicerp/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/cubicerp/cbc/cubicerp/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/cubicerp/cbc/cubicerp/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/cubicerp/cbc/cubicerp/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/cubicerp/cbc/cubicerp/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/cubicerp/cbc/cubicerp/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/cubicerp/cbc/cubicerp/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/cubicerp/cbc/cubicerp/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/cubicerp/cbc/cubicerp/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/cubicerp/cbc/cubicerp/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/cubicerp/cbc/cubicerp/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/cubicerp/cbc/cubicerp/addons/account/wizard/account_invoice_refund.py", line 125, in invoice_refund
    return self.compute_refund(data_refund)
  File "/home/cubicerp/cbc/cubicerp/addons/account/wizard/account_invoice_refund.py", line 60, in compute_refund
    refund = inv.refund(form.date_invoice, date, description, inv.journal_id.get_related_journal().id or inv.journal_id.id)
  File "/home/cubicerp/cbc/cubicerp/odoo/fields.py", line 2518, in __get__
    return record.ensure_one()._ids[0]
  File "/home/cubicerp/cbc/cubicerp/odoo/models.py", line 4268, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: account.journal(14, 12)
```
