### ISSUE TITLE
Error al instalar

### ISSUE THREAD

**Issue by PercyWoeds** [CubicERP/cubicerp#84]
hola tengo el siguiente error al tratar de instalar segun su manual, si me pueden ayudar por favor

./cubicerp-server -c .cubicerp_serverrc -d mycubic -u all -F
/usr/local/lib/python2.7/dist-packages/requests-2.20.1-py2.7.egg/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
2018-12-07 22:48:01,334 7378 INFO ? cubicerp: CubicERP version 9.2
2018-12-07 22:48:01,335 7378 INFO ? cubicerp: addons paths: ['/home/cubicerp3/.local/share/CubicERP/addons/9.2', u'/home/cubicerp3/cubicerp/openerp/addons', u'/home/cubicerp3/cubicerp/addons']
2018-12-07 22:48:01,335 7378 INFO ? cubicerp: database hostname: localhost
2018-12-07 22:48:01,335 7378 INFO ? cubicerp: database port: 5432
2018-12-07 22:48:01,335 7378 INFO ? cubicerp: database user: cubicerp3
2018-12-07 22:48:01,508 7378 INFO ? cubicerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2018-12-07 22:48:01,514 7378 ERROR ? cubicerp.sql_db: Connection to the database failed
Traceback (most recent call last):
  File "/home/cubicerp3/cubicerp/openerp/sql_db.py", line 560, in borrow
    result = psycopg2.connect(dsn=dsn, connection_factory=PsycoConnection)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: fe_sendauth: no password supplied

2018-12-07 22:48:01,515 7378 CRITICAL ? cubicerp.service.server: Failed to initialize database `mycubic`.
Traceback (most recent call last):
  File "/home/cubicerp3/cubicerp/openerp/service/server.py", line 937, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/cubicerp3/cubicerp/openerp/modules/registry.py", line 356, in new
    registry = Registry(db_name)
  File "/home/cubicerp3/cubicerp/openerp/modules/registry.py", line 81, in __init__
    cr = self.cursor()
  File "/home/cubicerp3/cubicerp/openerp/modules/registry.py", line 272, in cursor
    return self._db.cursor()
  File "/home/cubicerp3/cubicerp/openerp/sql_db.py", line 609, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/home/cubicerp3/cubicerp/openerp/sql_db.py", line 181, in __init__
    self._cnx = pool.borrow(dsn)
  File "/home/cubicerp3/cubicerp/openerp/sql_db.py", line 498, in _locked
    return fun(self, *args, **kwargs)
  File "/home/cubicerp3/cubicerp/openerp/sql_db.py", line 560, in borrow
    result = psycopg2.connect(dsn=dsn, connection_factory=PsycoConnection)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: fe_sendauth: no password supplied

^C2018-12-07 22:52:20,985 7378 INFO ? cubicerp.service.server: Initiating shutdown
2018-12-07 22:52:20,985 7378 INFO ? cubicerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

**Comment by lisbethgutierrez** [comment]
Estimado Percy,
consultarle que versión de CubicERP ha instalado?

Si ha instalado la v9.2 rama master, actualizar con el siguiente comando:
- cubicerp/cubicerp-server -c .cubicerp_serverrc -d mycubic -u all -F

Si ha instalado la v2018 rama trunk, actualizar con el siguiente comando:
- ./cubicerp-server -c .cubicerp_serverrc -d mycubic -u all

Saludos.

**Comment by PercyWoeds** [comment]
Hola

Use las instricciones de este manual.

https://github.com/CubicERP/cubicerp/blob/master/INSTALL_es.md

**Comment by lisbethgutierrez** [comment]
Excelente..!!
